export const tamilNaduData = {
  Ariyalur: ["Ariyalur", "Andimadam", "Sendurai", "Udayarpalayam"],
  Chengalpattu: [
    "Chengalpattu",
    "Thirukkalukundram",
    "Thirupporur",
    "Cheyyur",
    "Madhurantakam",
    "Pallavaram",
    "Tambaram",
    "Vandalur",
  ],
  Chennai: [
    "Ambattur",
    "Aminjikarai",
    "Ayanavaram",
    "Egmore",
    "Maduravoyal",
    "Mambalam",
    "Madhavaram",
    "Perambur",
    "Pursawalkam",
    "Thiruvottiyur",
    "Tondiarpet",
    "Alandur",
    "Guindy",
    "Mylapore",
    "Sholinganallur",
    "Velachery",
  ],
  Coimbatore: [
    "Annur",
    "Coimbatore North",
    "Mettupalayam",
    "Coimbatore South",
    "Madukarai",
    "Perur",
    "Sulur",
    "Anaimalai",
    "Kinathukadavu",
    "Pollachi",
    "Valparai",
  ],
  Cuddalore: [
    "Bhuvanagiri",
    "Chidambaram",
    "Kattumannarkoil",
    "Srimushnam",
    "Cuddalore",
    "Kurinjipadi",
    "Panruti",
    "Titagudi",
    "Veppur",
    "Vridhachalam",
  ],
  Dharmapuri: ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Palacode", "Pennagaram"],
  Dindigul: [
    "Athoor",
    "Batlagundu",
    "Dindigul East",
    "Dindigul West",
    "Guziliyamparai",
    "Kodaikanal",
    "Natham",
    "Nilakottai",
    "Oddanchatram",
    "Palani",
    "Vedasandur",
  ],
  Erode: [
    "Anthiyur",
    "Bhavani",
    "Erode",
    "Gobichettipalayam",
    "Kodumudi",
    "Modakurichi",
    "Nambiyur",
    "Perundurai",
    "Sathyamangalam",
    "Thalavadi",
  ],
  Kallakurichi: ["Kallakurichi", "Chinnaselam", "Kalvarayan Hills", "Sankarapuram", "Tirukoilur", "Ulundurpet"],
  Kanchipuram: ["Kanchipuram", "Kundrathur", "Sriperumbudur", "Uthiramerur", "Walajabad"],
  Kanyakumari: ["Agastheeswaram", "Kalkulam", "Killiyur", "Thovalai", "Vilavancode"],
  Karur: ["Aravakurichi", "Karur", "Krishnarayapuram", "Kulithalai", "Manmangalam"],
  Krishnagiri: [
    "Anchetti",
    "Bargur",
    "Denkanikottai",
    "Hosur",
    "Krishnagiri",
    "Pochampalli",
    "Shoolagiri",
    "Uthangarai",
  ],
  Madurai: [
    "Kalligudi",
    "Madurai East",
    "Madurai North",
    "Madurai South",
    "Madurai West",
    "Melur",
    "Peraiyur",
    "Thirumangalam",
    "Thiruparankundram",
    "Usilampatti",
    "Vadipatti",
  ],
  Mayiladuthurai: ["Kuthalam", "Mayiladuthurai", "Sirkali", "Tharangambadi"],
  Nagapattinam: ["Kilvelur", "Nagapattinam", "Thirukkuvalai", "Vedaranyam"],
  Namakkal: [
    "Kolli Hills",
    "Kumarapalayam",
    "Mohanur",
    "Namakkal",
    "Paramathi Velur",
    "Rasipuram",
    "Senthamangalam",
    "Tiruchengode",
  ],
  Nilgiris: ["Coonoor", "Gudalur", "Kotagiri", "Kundah", "Panthalur", "Udhagamandalam"],
  Perambalur: ["Alathur", "Kunnam", "Perambalur", "Veppanthattai"],
  Pudukkottai: [
    "Alangudi",
    "Aranthangi",
    "Avudaiyarkoil",
    "Gandarvakottai",
    "Iluppur",
    "Karambakudi",
    "Kulathur",
    "Manamelkudi",
    "Ponnamaravathi",
    "Pudukkottai",
    "Thirumayam",
    "Viralimalai",
  ],
  Ramanathapuram: [
    "Kadaladi",
    "Kamuthi",
    "Kilakarai",
    "Mandapam",
    "Mudukulathur",
    "Paramakudi",
    "Rajasingamangalam",
    "Ramanathapuram",
    "Rameswaram",
    "Tiruvadanai",
  ],
  Ranipet: ["Arakkonam", "Arcot", "Nemili", "Sholingur", "Walajah"],
  Salem: [
    "Attur",
    "Edappadi",
    "Gangavalli",
    "Kadaiyampatti",
    "Mettur",
    "Omalur",
    "Peddanaickenpalayam",
    "Salem",
    "Sankari",
    "Vazhapadi",
    "Yercaud",
  ],
  Sivaganga: [
    "Devakottai",
    "Ilayankudi",
    "Kalaiyarkovil",
    "Karaikudi",
    "Manamadurai",
    "Singampunari",
    "Sivaganga",
    "Thirupuvanam",
    "Tirupathur",
  ],
  Tenkasi: [
    "Alangulam",
    "Kadayanallur",
    "Sankarankovil",
    "Shencottai",
    "Sivagiri",
    "Thiruvengadam",
    "Veerakeralampudur",
  ],
  Thanjavur: [
    "Boothalur",
    "Kumbakonam",
    "Orathanadu",
    "Papanasam",
    "Pattukottai",
    "Peravurani",
    "Thanjavur",
    "Thiruvaiyaru",
    "Thiruvidaimarudur",
  ],
  Theni: ["Andipatti", "Bodinayakanur", "Periyakulam", "Theni", "Uthamapalayam"],
  Thoothukudi: [
    "Eral",
    "Ettayapuram",
    "Kayathar",
    "Kovilpatti",
    "Ottapidaram",
    "Sattankulam",
    "Srivaikuntam",
    "Thoothukudi",
    "Tiruchendur",
    "Vilathikulam",
  ],
  Tiruchirappalli: [
    "Lalgudi",
    "Manachanallur",
    "Manapparai",
    "Marungapuri",
    "Musiri",
    "Srirangam",
    "Thottiam",
    "Thuraiyur",
    "Tiruchirappalli",
    "Tiruverumbur",
  ],
  Tirunelveli: [
    "Ambasamudram",
    "Cheranmahadevi",
    "Manur",
    "Nanguneri",
    "Palayamkottai",
    "Radhapuram",
    "Thisayanvilai",
    "Tirunelveli",
  ],
  Tirupathur: ["Ambur", "Natrampalli", "Tirupathur", "Vaniyambadi"],
  Tiruppur: ["Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Tiruppur", "Udumalaipettai"],
  Tiruvallur: [
    "Avadi",
    "Gummidipoondi",
    "Pallipattu",
    "Ponneri",
    "Poonamallee",
    "R.K. Pet",
    "Tiruvallur",
    "Tiruttani",
    "Uthukottai",
  ],
  Tiruvannamalai: [
    "Arani",
    "Arni",
    "Chengam",
    "Chetpet",
    "Jamunamarathur",
    "Kalasapakkam",
    "Kilpennathur",
    "Polur",
    "Thandramet",
    "Thandrampet",
    "Tiruvannamalai",
    "Vandavasi",
    "Vembakkam",
  ],
  Tiruvarur: [
    "Koothanallur",
    "Mannargudi",
    "Nannilam",
    "Needamangalam",
    "Thiruthuraipoondi",
    "Tiruvarur",
    "Valangaiman",
  ],
  Vellore: ["Aanikattu", "Gudiyatham", "K.V. Kuppam", "Katpadi", "Pernambut", "Vellore"],
  Viluppuram: [
    "Gingee",
    "Kandachipuram",
    "Marakkanam",
    "Melmalaiyanur",
    "Tindivanam",
    "Vanur",
    "Vikravandi",
    "Viluppuram",
  ],
  Virudhunagar: [
    "Aruppukkottai",
    "Kariapatti",
    "Rajapalayam",
    "Sathur",
    "Sivakasi",
    "Srivilliputhur",
    "Tiruchuli",
    "Vembakottai",
    "Virudhunagar",
    "Watrap",
  ],
}

export const serviceCenters = {
  "Post Office": [
    "Chennai GPO",
    "Coimbatore Head Post Office",
    "Madurai Central Post Office",
    "Salem Main Post Office",
    "Tiruchirappalli Head Post Office",
    "Tirunelveli Head Post Office",
    "Vellore Main Post Office",
    "Thanjavur Head Post Office",
    "Erode Main Post Office",
    "Tiruppur Head Post Office",
  ],
  "E-Center": [
    "Chennai E-Seva Center",
    "Coimbatore Digital Center",
    "Madurai E-Services Hub",
    "Salem Technology Center",
    "Tiruchirappalli Digital Hub",
    "Tirunelveli E-Center",
    "Vellore Digital Services",
    "Thanjavur E-Hub",
    "Erode Digital Center",
    "Tiruppur E-Services",
  ],
}

export const timeSlots = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "01:00 PM",
  "01:30 PM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
  "04:30 PM",
  "05:00 PM",
  "05:30 PM",
  "06:00 PM",
  "06:30 PM",
  "07:00 PM",
  "07:30 PM",
  "08:00 PM",
  "08:30 PM",
  "09:00 PM",
]

export const serviceTypes = ["Aadhaar Update", "Voter ID Registration", "Ration Card Application"]

export const talukCenters = {
  // Chennai District
  Ambattur: ["Chennai E-Seva Center - Ambattur", "Ambattur Post Office"],
  Aminjikarai: ["Chennai E-Seva Center - Aminjikarai", "Aminjikarai Post Office"],
  Ayanavaram: ["Chennai E-Seva Center - Ayanavaram", "Ayanavaram Post Office"],
  Egmore: ["Chennai GPO", "Egmore E-Services Hub"],
  Maduravoyal: ["Chennai E-Seva Center - Maduravoyal", "Maduravoyal Post Office"],
  Mambalam: ["Chennai E-Seva Center - Mambalam", "Mambalam Post Office"],
  Madhavaram: ["Chennai E-Seva Center - Madhavaram", "Madhavaram Post Office"],
  Perambur: ["Chennai E-Seva Center - Perambur", "Perambur Post Office"],
  Pursawalkam: ["Chennai E-Seva Center - Pursawalkam", "Pursawalkam Post Office"],
  Thiruvottiyur: ["Chennai E-Seva Center - Thiruvottiyur", "Thiruvottiyur Post Office"],
  Tondiarpet: ["Chennai E-Seva Center - Tondiarpet", "Tondiarpet Post Office"],
  Alandur: ["Chennai E-Seva Center - Alandur", "Alandur Post Office"],
  Guindy: ["Chennai E-Seva Center - Guindy", "Guindy Post Office"],
  Mylapore: ["Chennai E-Seva Center - Mylapore", "Mylapore Post Office"],
  Sholinganallur: ["Chennai E-Seva Center - Sholinganallur", "Sholinganallur Post Office"],
  Velachery: ["Chennai E-Seva Center - Velachery", "Velachery Post Office"],

  // Coimbatore District
  Annur: ["Annur E-Center", "Annur Post Office"],
  "Coimbatore North": ["Coimbatore Digital Center", "Coimbatore Head Post Office"],
  Mettupalayam: ["Mettupalayam E-Center", "Mettupalayam Post Office"],
  "Coimbatore South": ["Coimbatore Digital Center - South", "Coimbatore South Post Office"],
  Madukarai: ["Madukarai E-Center", "Madukarai Post Office"],
  Perur: ["Perur E-Center", "Perur Post Office"],
  Sulur: ["Sulur E-Center", "Sulur Post Office"],
  Anaimalai: ["Anaimalai E-Center", "Anaimalai Post Office"],
  Kinathukadavu: ["Kinathukadavu E-Center", "Kinathukadavu Post Office"],
  Pollachi: ["Pollachi E-Center", "Pollachi Post Office"],
  Valparai: ["Valparai E-Center", "Valparai Post Office"],

  // Madurai District
  Kalligudi: ["Kalligudi E-Center", "Kalligudi Post Office"],
  "Madurai East": ["Madurai E-Services Hub - East", "Madurai East Post Office"],
  "Madurai North": ["Madurai E-Services Hub - North", "Madurai North Post Office"],
  "Madurai South": ["Madurai Central Post Office", "Madurai E-Services Hub - South"],
  "Madurai West": ["Madurai E-Services Hub - West", "Madurai West Post Office"],
  Melur: ["Melur E-Center", "Melur Post Office"],
  Peraiyur: ["Peraiyur E-Center", "Peraiyur Post Office"],
  Thirumangalam: ["Thirumangalam E-Center", "Thirumangalam Post Office"],
  Thiruparankundram: ["Thiruparankundram E-Center", "Thiruparankundram Post Office"],
  Usilampatti: ["Usilampatti E-Center", "Usilampatti Post Office"],
  Vadipatti: ["Vadipatti E-Center", "Vadipatti Post Office"],

  // Salem District
  Attur: ["Attur E-Center", "Attur Post Office"],
  Edappadi: ["Edappadi E-Center", "Edappadi Post Office"],
  Gangavalli: ["Gangavalli E-Center", "Gangavalli Post Office"],
  Kadaiyampatti: ["Kadaiyampatti E-Center", "Kadaiyampatti Post Office"],
  Mettur: ["Mettur E-Center", "Mettur Post Office"],
  Omalur: ["Omalur E-Center", "Omalur Post Office"],
  Peddanaickenpalayam: ["Peddanaickenpalayam E-Center", "Peddanaickenpalayam Post Office"],
  Salem: ["Salem Technology Center", "Salem Main Post Office"],
  Sankari: ["Sankari E-Center", "Sankari Post Office"],
  Vazhapadi: ["Vazhapadi E-Center", "Vazhapadi Post Office"],
  Yercaud: ["Yercaud E-Center", "Yercaud Post Office"],

  // Default centers for other taluks
  default: ["District E-Center", "District Post Office"],
}
